apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: infra
data:
  traefik.yaml: | 
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    log:
      level: debug

    accessLog:
      fields:
        defaultMode: keep
        headers:
          defaultMode: keep

    ping: {}

    api:
      insecure: true
      dashboard: true
      debug: true

    entryPoints:
      traefik:
        address: ":8090"
      websecure:
        address: ":443"
      http:
        address: ":8080"
    tls:
      options:
        myTLSOption:
          minVersion: VersionTLS12
          alpnProtocols:
            - http/1.1
            - h2
    
    providers:
      kubernetesIngress: {}
      file:
        filename: "/config/tls.yaml"
        watch: true
