apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-config
  namespace: infra
data:
  tls.yaml: |-
    tls:
      stores:
        default: {}
      certificates:
        - certFile: /ssl-certs/tls.crt
          keyFile: /ssl-certs/tls.key
          stores:
            - default
      options:
        default:
          clientAuth:
            clientAuthType: NoClientCert