apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-config
  namespace: infra
data:
  tls.yaml: |-
    tls:
      options:
        default:
          clientAuth:
            clientAuthType: NoClientCert