apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: data
    name: data-volume-mongodb-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    hostPath:
      path: /opt/data/mongo-data-0
      type: ""
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    labels:
      type: logs
    name: logs-volume-mongodb-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    hostPath:
      path: /opt/data/mongo-logs-0
      type: ""
    persistentVolumeReclaimPolicy: Retain
    storageClassName: default
    volumeMode: Filesystem