apiVersion: v1
kind: Service
metadata:
  name: squid-proxy
  namespace: infra
spec:
  selector:
    app: squid-proxy
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer