---
# Source: gx-registry/templates/deployment-registry.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gx-registry
  namespace: infra
  labels:
    app.kubernetes.io/name: gx-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gx-registry
  template:
    metadata:
      annotations:
        randstring: "AZtvXjSD"
      labels:
        app.kubernetes.io/name: gx-registry
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-kubo
          image: busybox:1.37.0
          command:
            - sh
            - -c
            - until nc -z gx-registry-kubo 5001; do echo waiting for Kubo; sleep 2; done;
        - name: local-trust
          image: quay.io/wi_stefan/gaiax-local-trust:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: ROOT_CA
              value: "MIIFnDCCA4SgAwIBAgIBATANBgkqhkiG9w0BAQsFADBnMQswCQYDVQQGEwJERTEPMA0GA1UECAwGU2F4b255MRAwDgYDVQQHDAdEcmVzZGVuMRMwEQYDVQQKDApGSUNPREVTIENBMRMwEQYDVQQDDApGSUNPREVTLUNBMQswCQYDVQQFEwIwMTAeFw0yNjAyMjUxNDM1NTBaFw0zNjAyMjMxNDM1NTBaMGcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZTYXhvbnkxEDAOBgNVBAcMB0RyZXNkZW4xEzARBgNVBAoMCkZJQ09ERVMgQ0ExEzARBgNVBAMMCkZJQ09ERVMtQ0ExCzAJBgNVBAUTAjAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvLPxmWkECMWVZpRSZkqy21eF3bS5imsZoRZCxPM9YU7flVujHuw8DQx3cWlO4IdiH5gQix7WFb2bJn7iXRDWfYW7SIDRTSKu21Q1pc9cJjVXMBSbfC80Dp8yX2zdAeraGfGY+yz+rnsjFlXtssK+4Gf2ut2Rtb7/ssqKLqt2ybzj2GwuubC79r03MchJ8O8lUROwy67ZUrwPlCg0POBtAOzJNueaBPhlPVPV/XeXQLdcK9utzu5Uv+oklgnepu9k/B/oVJO7lDdkcW18ESVdXfl/G7d2qGwE+CyV9KKD/qxrTB6zOHoLhaUrvcb+EmEYYUiUF8W8OGbMzIT3qpLOwaTk0ESVZO9YSc4fOlHz8MrUCxzRpKheMhRC6HCggTlyIvh0Wwf5TRieODGkBFpjYCkChxHO/iQ6hEc2VLdokZIJzDt43Qltj9+W3VOYEQaTBtWWNWyAYzgJGeGNRavXVz65gz+HfUKlkv6rcflMXojCYAphj2ZbRnZfzg8RdvHHWPfYpoexEaaTFsyjrufUCa7iAguO7P4e+EE3JLdHJwBhOb018cCyK5Hemiu+nvoYDcp8aiPdto8ARbvaubIdiwdsZ8X9FG0HhAsc3YTqN6BykDatA/kK6zJc/kOItbFSO1ODL7r4NTv799wsyip7sDfqOCYEQ97G7SY17JulHf0CAwEAAaNTMFEwHQYDVR0OBBYEFKXw6Nql+0B1mvtDFDSVNsHV9aTCMB8GA1UdIwQYMBaAFKXw6Nql+0B1mvtDFDSVNsHV9aTCMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAEhbFwa5ZjJYF5X/0ggZLQE3BSPl4yfA0kZGxvjmr/H2FpVwSRHatxV6IKN3o2e6R355GpbjfX+8BSEoVBytbITT36AVqYahGe+D3JcbOE6Se5wfSR5cwe3QnGx1ge9jbnPoIFcz7xpkT41t9YLkA1WoUz9bybTK/BZ1gJG0eJcPI2MZSQsyBMPZBGNKxElqGMp/8KxcmiHKROmUqN4rhIKq1XpkyMwsuahD1hyDX0zR/DLvpphTSWhag45CYoAwj4mijCRn7NISctU/7GRyOmvgXJ4eNG9UuxnOTPMS0UXk/1/OHrFMX183wjoKqKSfxabmV2bvgzbFogiPCxsD7nXey+NZz0Qb+gxFNQm8m3WtB4tIckUvxJnIcKB2idGdmmAIAyzOmvbaea0n3KZyVL0yBZMQqIyAkpoOz4LQsar8JhSiqQMWHJFu155qxNivBrTDWp0RuLnZfuwAkJMODbHTwSfMUHrwzDUE8v3PFbOHd78kvGywtOPBhHOmNzUZ+qx4myRgR7U2Pe9R9w4B3zz56b2oIQoUCxSMWzwxMN2JsxwK2YQXCE9XI2MeGeOiZn0E/igU4eN8FDu8NGkkgslc3jhbJl0/KmOJ7nl6SMdZtXJO2UdBFhO8UKuar3l62pcBtKiELwgzmQsJ05i1/NQjLcu3c+hTXkYuD1qyVFFX"
          volumeMounts:
            - name: trust-anchor
              mountPath: /out
      containers:
        - name: gx-registry
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: "registry.gitlab.com/gaia-x/lab/compliance/gx-registry:v2.8.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: BASE_URI
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: BASE_URL
              value: "https://registry.127.0.0.1.nip.io/v2"
            - name: APP_PATH
              value: "/v2"
            - name: evsslonly
              value: "false"
            - name: revocationListURL
              value:
            - name: trustedIssuersURL
              value:
            - name: KUBO_HOST
              value: gx-registry-kubo
            - name: APP_BRANCH
              value: "main"
            - name: ONTOLOGY_VERSION
              value: "development"
            - name: PRIVATE_KEY_ALGORITHM
              value: "PS256"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: HTTPS_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
            - name: HTTP_PROXY
              value: "http://squid-proxy.infra.svc.cluster.local:8888"
          envFrom:
            - secretRef:
                name: gx-registry-keypair
          volumeMounts:
            - name: registry-ipfs-data
              mountPath: /data/ipfs
            - name: trust-anchor
              mountPath: /data/ipfs/registry/
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          readinessProbe:
            periodSeconds: 15
            initialDelaySeconds: 15
            failureThreshold: 10
            successThreshold: 1
            httpGet:
              path: /v2
              port: 3000
          resources: {}
      volumes:
        - name: trust-anchor
          emptyDir: {}
        - name: registry-ipfs-data
          emptyDir: {}
