---
# Source: gx-registry/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gx-registry
  namespace: infra
  labels:
    app.kubernetes.io/name: gx-registry
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: "registry.127.0.0.1.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gx-registry
                port:
                  number: 3000
