apiVersion: v2
name: data-space-connector
description: Umbrella Chart for the FIWARE Data Space Connector, combining all essential parts to be used by a participant.
type: application
version: 8.5.2
dependencies:
  - name: decentralized-iam
    alias: decentralizedIam
    condition: decentralizedIam.enabled
    version: 2.0.1
    repository: https://fiware.github.io/decentralized-iam
  # data-service
  - name: scorpio-broker-aaio
    alias: scorpio
    condition: scorpio.enabled
    repository: https://fiware.github.io/helm-charts
    version: 0.4.12
  # issuance
  - name: keycloak
    condition: keycloak.enabled
    version: 25.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
  # contract management
  - name: tm-forum-api
    condition: tm-forum-api.enabled
    version: 0.16.3
    repository: https://fiware.github.io/helm-charts
  - name: contract-management
    condition: contract-management.enabled
    version: 3.5.15
    repository: https://fiware.github.io/helm-charts
  # marketplace
  - name: business-api-ecosystem
    alias: marketplace
    condition: marketplace.enabled
    version: 0.11.26
    repository: https://fiware.github.io/helm-charts
  - name: community-operator
    alias: mongo-operator
    condition: mongo-operator.enabled
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
  # dsp
  - name: fdsc-edc
    condition: fdsc-edc.enabled
    version: 0.1.3
    repository: https://fiware.github.io/helm-charts
  - name: vault
    alias: vault
    condition: vault.enabled
    version: 0.29.1
    repository: https://helm.releases.hashicorp.com
  # did-helper
  - name: did-helper
    alias: did
    condition: did.enabled
    version: 0.1.13
    repository: https://fiware.github.io/helm-charts
  # cert-manager
  - name: cert-manager
    alias: cert-manager
    condition: cert-manager.enabled
    version: 1.20.0
    repository: https://charts.jetstack.io
