{{- if eq .Values.dss.crl.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: crl-provider
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.dss.crl.secret | nindent 2 }}
{{- end }}