{{- if .Values.dataSpaceConfig.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dsconfig
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: dsconfig
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dsconfig
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: default
      containers:
        - name: dsconfig-static
          imagePullPolicy: Always
          image: "lipanski/docker-static-website:2.1.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: dsconfig-json
              mountPath: /home/static/.well-known/data-space-configuration
      volumes:
        - name: dsconfig-json
          configMap:
            name: dsconfig
{{- end }}
