{{- if .Values.dataSpaceConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsconfig
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  data-space-configuration.json: |-
    {
      "supported_models": {{ .Values.dataSpaceConfig.supportedModels | toJson }},
      "supported_protocols": {{ .Values.dataSpaceConfig.supportedProtocols | toJson }},
      "authentication_protocols": {{ .Values.dataSpaceConfig.authenticationProtocols | toJson }}
    }
{{- end }}
