{{- if .Values.elsi.keystore }}
apiVersion: v1
kind: Secret
metadata:
  name: elsi-secret
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.elsi.keystore | nindent 2 }}
{{- end }}