{{- if (eq .Values.identityhub.enabled true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: identityhub-logging
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app.kubernetes.io/name: identityhub
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  logging.properties: |-
  {{- if .Values.identityhub.logging.enabled }}
    handlers={{- join "," .Values.identityhub.logging.handlers }}
    {{- $console := "java.util.logging.ConsoleHandler" }}
    {{- $file := "java.util.logging.FileHandler" }}
    {{- if has $console .Values.identityhub.logging.handlers }}
    # Console Handler Config
    {{- range $key, $value := index .Values.identityhub.logging.handlersConfig $console }}
    {{ $console }}.{{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
    {{- if has $file .Values.identityhub.logging.handlers }}
    # File Handler Config
    {{- range $key, $value := index .Values.identityhub.logging.handlersConfig $file }}
    {{ $file }}.{{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}
    # Formatter Configs
    {{- range $formatter, $config := .Values.identityhub.logging.formatters }}
    {{ $formatter }}.format = {{ $config.format }}
    {{- end }}
    # Root level and Package level control
    .level={{- .Values.identityhub.logging.level }}
    {{- range $pkg, $level := .Values.identityhub.logging.logLevels }}
    {{ $pkg }}.level = {{ $level }}
    {{- end }}
  {{- else }}
    {{ .Values.identityhub.logging.default | indent 4 }}
  {{- end }}
{{- end }}