{{- if and .Values.rainbow.enabled .Values.rainbow.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rainbow
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.rainbow.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rainbow
                port:
                  name: http
{{- end }}
