{{- if and (eq .Values.rainbow.enabled true) (eq .Values.rainbow.ccs.enabled true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rainbow.ccs.configMap }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dsc.labels" . | nindent 4 }}
data:
  init.sh: |-
    # credentials config service registration
    curl -X 'POST' \
      '{{ .Values.rainbow.ccs.endpoint }}/service' \
      -H 'accept: */*' \
      -H 'Content-Type: application/json' \
      -d '{
      "id": {{ .Values.rainbow.ccs.id | quote }},
      "defaultOidcScope": {{ .Values.rainbow.ccs.defaultOidcScope.name | quote }},
      {{- if and (.Values.rainbow.ccs.defaultOidcScope.credentialType) (.Values.rainbow.ccs.defaultOidcScope.trustedParticipantsLists) (.Values.rainbow.ccs.defaultOidcScope.trustedIssuersLists) -}}
      "oidcScopes": {
        {{ .Values.rainbow.ccs.defaultOidcScope.name | quote }}: [
          {
            "type": {{ .Values.rainbow.ccs.defaultOidcScope.credentialType | quote }},
            "trustedParticipantsLists": [
              {{ .Values.rainbow.ccs.defaultOidcScope.trustedParticipantsLists | quote }}
            ],
            "trustedIssuersLists": [
              {{ .Values.rainbow.ccs.defaultOidcScope.trustedIssuersLists | quote }}
            ]
          }
        ]
      }
      {{- end }}
      {{- if .Values.rainbow.ccs.oidcScopes -}}
      "oidcScopes": {{- toJson .Values.rainbow.ccs.oidcScopes }}
      {{- end }}
    }'

{{- end }}