{{- if and .Values.statusListServer.enabled .Values.statusListServer.redis.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: status-list-redis
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: status-list-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: status-list-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: default
      containers:
        - name: redis
          imagePullPolicy: {{ .Values.statusListServer.redis.image.pullPolicy }}
          image: "{{ .Values.statusListServer.redis.image.repository }}:{{ .Values.statusListServer.redis.image.tag }}"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- with .Values.statusListServer.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: status-list-redis
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: status-list-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
