package org.fiware.dataspace.it.components.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Request body for IdentityHub participant registration.
 * Corresponds to the participant creation payload documented in DSP_INTEGRATION.md
 * and generated by the {@code get-participant-create.sh} script.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class ParticipantCreate {

    /** Roles assigned to the participant (e.g., ["admin"]). */
    private List<String> role;

    /** Service endpoints exposed by the participant (e.g., CredentialService). */
    private List<ServiceEndpoint> serviceEndpoints;

    /** Whether the participant is active. */
    private boolean active;

    /** The participant's unique identifier (typically a DID). */
    private String participantId;

    /** The participant's DID (Decentralized Identifier). */
    private String did;

    /** The participant's cryptographic key information. */
    private KeyDescriptor key;

    /**
     * A service endpoint entry for the participant.
     */
    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    @Builder
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ServiceEndpoint {

        /** The type of service (e.g., "CredentialService"). */
        private String type;

        /** The URL of the service endpoint. */
        private String serviceEndpoint;

        /** Unique identifier for this service endpoint. */
        private String id;
    }

    /**
     * Describes a cryptographic key for the participant, including both the key ID,
     * private key alias (for Vault lookup), and the public key in JWK format.
     */
    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    @Builder
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class KeyDescriptor {

        /** The key ID, typically in the form "{did}#{alias}". */
        private String keyId;

        /** The alias used to look up the private key in the Vault. */
        private String privateKeyAlias;

        /** The public key in JWK (JSON Web Key) format. */
        private Map<String, Object> publicKeyJwk;
    }
}
