package org.fiware.dataspace.it.components;

import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;

/**
 * Helper class for interacting with Kubernetes resources during integration tests.
 * <p>
 * Uses {@code kubectl} to retrieve secrets and other resources from the local k3s cluster.
 * This replaces the previous approach of reading keys from local files generated by
 * {@code helpers/certs/generate-certs.sh}, as keys are now managed by cert-manager.
 */
@Slf4j
public class KubernetesHelper {

    /**
     * Timeout in seconds for kubectl commands.
     */
    private static final int KUBECTL_TIMEOUT_SECONDS = 30;

    /**
     * Relative path from the Maven module directory to the k3s kubeconfig file
     * generated by the k3s-maven-plugin.
     */
    private static final String K3S_KUBECONFIG_RELATIVE_PATH = "target/k3s.yaml";

    private KubernetesHelper() {
        // prevent instantiation
    }

    /**
     * Resolves the path to the k3s kubeconfig file.
     * <p>
     * Checks for the {@code KUBECONFIG} environment variable first.
     * Falls back to {@code target/k3s.yaml} relative to the current working directory
     * (or its parent if running from the {@code it} subdirectory).
     *
     * @return the absolute path to the kubeconfig file
     * @throws IllegalStateException if no kubeconfig file can be found
     */
    private static String resolveKubeconfig() {
        String envKubeconfig = System.getenv("KUBECONFIG");
        if (envKubeconfig != null && Files.exists(Paths.get(envKubeconfig))) {
            return envKubeconfig;
        }

        Path currentDir = Paths.get(System.getProperty("user.dir"));
        Path kubeconfigPath = currentDir.resolve(K3S_KUBECONFIG_RELATIVE_PATH);
        if (Files.exists(kubeconfigPath)) {
            return kubeconfigPath.toAbsolutePath().toString();
        }

        // If running from the 'it' subdirectory, try the parent
        Path parentKubeconfigPath = currentDir.getParent().resolve("it").resolve(K3S_KUBECONFIG_RELATIVE_PATH);
        if (Files.exists(parentKubeconfigPath)) {
            return parentKubeconfigPath.toAbsolutePath().toString();
        }

        throw new IllegalStateException(
                String.format("k3s kubeconfig not found at '%s' or via KUBECONFIG env var.", kubeconfigPath));
    }

    /**
     * Fetches the {@code tls.key} field from a cert-manager TLS secret in the given namespace.
     * <p>
     * Executes {@code kubectl --kubeconfig <path> get secret <secretName> -n <namespace> -o jsonpath='{.data.tls\.key}'}
     * and Base64-decodes the result to obtain the PEM-encoded private key.
     *
     * @param namespace  the Kubernetes namespace containing the secret (e.g., {@code consumer})
     * @param secretName the name of the TLS secret (e.g., {@code signing-key})
     * @return the PEM-encoded private key content
     * @throws IOException          if the kubectl process cannot be started or its output cannot be read
     * @throws InterruptedException if the kubectl process is interrupted
     * @throws IllegalStateException if kubectl returns a non-zero exit code or empty output
     */
    public static String fetchTlsKeyFromSecret(String namespace, String secretName)
            throws IOException, InterruptedException {
        String kubeconfig = resolveKubeconfig();
        ProcessBuilder processBuilder = new ProcessBuilder(
                "kubectl", "--kubeconfig", kubeconfig,
                "get", "secret", secretName,
                "-n", namespace,
                "-o", "jsonpath={.data.tls\\.key}"
        );
        processBuilder.redirectErrorStream(true);
        Process process = processBuilder.start();

        String base64Output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8).trim();

        boolean finished = process.waitFor(KUBECTL_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        if (!finished) {
            process.destroyForcibly();
            throw new IllegalStateException(
                    String.format("kubectl timed out after %d seconds fetching secret '%s' in namespace '%s'.",
                            KUBECTL_TIMEOUT_SECONDS, secretName, namespace));
        }

        int exitCode = process.exitValue();
        if (exitCode != 0) {
            throw new IllegalStateException(
                    String.format("kubectl failed with exit code %d fetching secret '%s' in namespace '%s': %s",
                            exitCode, secretName, namespace, base64Output));
        }

        if (base64Output.isEmpty()) {
            throw new IllegalStateException(
                    String.format("Empty tls.key in secret '%s' in namespace '%s'.", secretName, namespace));
        }

        byte[] decodedBytes = java.util.Base64.getDecoder().decode(base64Output);
        String pemContent = new String(decodedBytes, StandardCharsets.UTF_8);

        log.debug("Successfully fetched tls.key from secret '{}' in namespace '{}'.", secretName, namespace);
        return pemContent;
    }
}
