package org.fiware.dataspace.it.components;

import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;

/**
 * Helper class for interacting with Kubernetes resources during integration tests.
 * <p>
 * Uses {@code kubectl} to retrieve secrets and other resources from the local k3s cluster.
 * This replaces the previous approach of reading keys from local files generated by
 * {@code helpers/certs/generate-certs.sh}, as keys are now managed by cert-manager.
 */
@Slf4j
public class KubernetesHelper {

    /**
     * Timeout in seconds for kubectl commands.
     */
    private static final int KUBECTL_TIMEOUT_SECONDS = 30;

    /**
     * Relative path from the Maven module directory to the k3s kubeconfig file
     * generated by the k3s-maven-plugin.
     */
    private static final String K3S_KUBECONFIG_RELATIVE_PATH = "target/k3s.yaml";

    /**
     * How long to wait for a port-forward to start accepting connections.
     */
    private static final int PORT_FORWARD_TIMEOUT_SECONDS = 30;

    /**
     * How long to wait between probes of a starting port-forward.
     */
    private static final long PORT_FORWARD_PROBE_INTERVAL_MS = 250;

    /**
     * Connect timeout when probing whether a port-forward is up.
     */
    private static final int PORT_FORWARD_PROBE_TIMEOUT_MS = 500;

    private KubernetesHelper() {
        // prevent instantiation
    }

    /**
     * Resolves the path to the k3s kubeconfig file.
     * <p>
     * Checks for the {@code KUBECONFIG} environment variable first.
     * Falls back to {@code target/k3s.yaml} relative to the current working directory
     * (or its parent if running from the {@code it} subdirectory).
     *
     * @return the absolute path to the kubeconfig file
     * @throws IllegalStateException if no kubeconfig file can be found
     */
    private static String resolveKubeconfig() {
        String envKubeconfig = System.getenv("KUBECONFIG");
        if (envKubeconfig != null && Files.exists(Paths.get(envKubeconfig))) {
            return envKubeconfig;
        }

        Path currentDir = Paths.get(System.getProperty("user.dir"));
        Path kubeconfigPath = currentDir.resolve(K3S_KUBECONFIG_RELATIVE_PATH);
        if (Files.exists(kubeconfigPath)) {
            return kubeconfigPath.toAbsolutePath().toString();
        }

        // If running from the 'it' subdirectory, try the parent
        Path parentKubeconfigPath = currentDir.getParent().resolve("it").resolve(K3S_KUBECONFIG_RELATIVE_PATH);
        if (Files.exists(parentKubeconfigPath)) {
            return parentKubeconfigPath.toAbsolutePath().toString();
        }

        throw new IllegalStateException(
                String.format("k3s kubeconfig not found at '%s' or via KUBECONFIG env var.", kubeconfigPath));
    }

    /**
     * Fetches the {@code tls.key} field from a cert-manager TLS secret in the given namespace.
     * <p>
     * Executes {@code kubectl --kubeconfig <path> get secret <secretName> -n <namespace> -o jsonpath='{.data.tls\.key}'}
     * and Base64-decodes the result to obtain the PEM-encoded private key.
     *
     * @param namespace  the Kubernetes namespace containing the secret (e.g., {@code consumer})
     * @param secretName the name of the TLS secret (e.g., {@code signing-key})
     * @return the PEM-encoded private key content
     * @throws IOException          if the kubectl process cannot be started or its output cannot be read
     * @throws InterruptedException if the kubectl process is interrupted
     * @throws IllegalStateException if kubectl returns a non-zero exit code or empty output
     */
    public static String fetchTlsKeyFromSecret(String namespace, String secretName)
            throws IOException, InterruptedException {
        String kubeconfig = resolveKubeconfig();
        ProcessBuilder processBuilder = new ProcessBuilder(
                "kubectl", "--kubeconfig", kubeconfig,
                "get", "secret", secretName,
                "-n", namespace,
                "-o", "jsonpath={.data.tls\\.key}"
        );
        processBuilder.redirectErrorStream(true);
        Process process = processBuilder.start();

        String base64Output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8).trim();

        boolean finished = process.waitFor(KUBECTL_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        if (!finished) {
            process.destroyForcibly();
            throw new IllegalStateException(
                    String.format("kubectl timed out after %d seconds fetching secret '%s' in namespace '%s'.",
                            KUBECTL_TIMEOUT_SECONDS, secretName, namespace));
        }

        int exitCode = process.exitValue();
        if (exitCode != 0) {
            throw new IllegalStateException(
                    String.format("kubectl failed with exit code %d fetching secret '%s' in namespace '%s': %s",
                            exitCode, secretName, namespace, base64Output));
        }

        if (base64Output.isEmpty()) {
            throw new IllegalStateException(
                    String.format("Empty tls.key in secret '%s' in namespace '%s'.", secretName, namespace));
        }

        byte[] decodedBytes = java.util.Base64.getDecoder().decode(base64Output);
        String pemContent = new String(decodedBytes, StandardCharsets.UTF_8);

        log.debug("Successfully fetched tls.key from secret '{}' in namespace '{}'.", secretName, namespace);
        return pemContent;
    }

    /**
     * A running {@code kubectl port-forward}, closed when the test is done with it.
     */
    public record PortForward(Process process, String target, int localPort) implements AutoCloseable {

        @Override
        public void close() {
            process.destroy();
            log.debug("Closed port-forward to {} on {}.", target, localPort);
        }
    }

    /**
     * Forwards a local port to a service in the cluster, and returns once it accepts connections.
     *
     * <p>Needed for endpoints that are deliberately not published: the consent-manager's
     * unauthenticated onboarding API, and the provider consent-facade, whose NetworkPolicy admits
     * only the APISIX pods and the OwnerResolver. A port-forward is proxied by the kubelet, so the
     * traffic originates from the node and the policy's pod selectors do not match it - which is
     * exactly how the documented walkthrough reaches them.
     *
     * @param namespace  namespace of the service
     * @param service    name of the service
     * @param localPort  port to open on the test machine
     * @param remotePort port of the service
     * @return the running forward; close it to stop forwarding
     * @throws IOException          if kubectl cannot be started
     * @throws InterruptedException if waiting for the forward is interrupted
     * @throws IllegalStateException if the forward does not come up in time
     */
    public static PortForward portForward(String namespace, String service, int localPort, int remotePort)
            throws IOException, InterruptedException {
        String kubeconfig = resolveKubeconfig();
        String target = namespace + "/svc/" + service + ":" + remotePort;
        ProcessBuilder processBuilder = new ProcessBuilder(
                "kubectl", "--kubeconfig", kubeconfig,
                "-n", namespace,
                "port-forward", "svc/" + service, localPort + ":" + remotePort
        );
        processBuilder.redirectErrorStream(true);
        processBuilder.redirectOutput(ProcessBuilder.Redirect.DISCARD);
        Process process = processBuilder.start();

        long deadline = System.currentTimeMillis() + PORT_FORWARD_TIMEOUT_SECONDS * 1000L;
        while (System.currentTimeMillis() < deadline) {
            if (!process.isAlive()) {
                throw new IllegalStateException(
                        String.format("kubectl port-forward to %s exited with %d.", target, process.exitValue()));
            }
            try (Socket probe = new Socket()) {
                probe.connect(new InetSocketAddress("127.0.0.1", localPort), PORT_FORWARD_PROBE_TIMEOUT_MS);
                log.debug("Port-forward to {} is up on {}.", target, localPort);
                return new PortForward(process, target, localPort);
            } catch (IOException notUpYet) {
                Thread.sleep(PORT_FORWARD_PROBE_INTERVAL_MS);
            }
        }
        process.destroyForcibly();
        throw new IllegalStateException(
                String.format("Port-forward to %s did not accept connections within %d seconds.",
                        target, PORT_FORWARD_TIMEOUT_SECONDS));
    }
}
