apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-credential
  namespace: "consumer"
data:
  get-credential.sh: |-
    #!/bin/sh

    wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.8.1/jq-linux64
    chmod +x ./jq
    
    access_token=$(curl -k -X POST "http://consumer-keycloak:8080/realms/test-realm/protocol/openid-connect/token" \
      --header 'Accept: */*' \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --data grant_type=password \
      --data client_id=account-console \
      --data username=employee \
      --data scope=openid \
      --data password=test | ./jq '.access_token' -r)

    echo AT $access_token

    offer_uri=$(curl -k -X GET "http://consumer-keycloak:8080/realms/test-realm/protocol/oid4vc/credential-offer-uri?credential_configuration_id=marketplace-credential" \
      --header "Authorization: Bearer ${access_token}" | ./jq '"\(.issuer)\(.nonce)"' -r)

    replaced_host_url=$(echo "$offer_uri" | sed -E "s|^https?://[^/]+|http://consumer-keycloak:8080|")

    echo OU $replaced_host_url

    export pre_authorized_code=$(curl -k -X GET ${replaced_host_url} \
      --header "Authorization: Bearer ${access_token}" | ./jq '.grants."urn:ietf:params:oauth:grant-type:pre-authorized_code"."pre-authorized_code"' -r)

    echo PAC $pre_authorized_code

    credential_access_token=$(curl -k -X POST "http://consumer-keycloak:8080/realms/test-realm/protocol/openid-connect/token" \
      --header 'Accept: */*' \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --data grant_type=urn:ietf:params:oauth:grant-type:pre-authorized_code \
      --data pre-authorized_code=${pre_authorized_code} | ./jq '.access_token' -r)

    echo CAT $credential_access_token

    curl -s -k -X POST "http://consumer-keycloak:8080/realms/test-realm/protocol/oid4vc/credential" \
      --header 'Accept: */*' \
      --header 'Content-Type: application/json' \
      --header "Authorization: Bearer ${credential_access_token}" \
      --data "{\"credential_identifier\":\"marketplace-credential\", \"format\":\"jwt_vc\"}" | ./jq '.credential' -r > $1/marketplace-credential.jwt

    if [ -s $1/marketplace-credential.jwt ]; then 
      cat $1/marketplace-credential.jwt
    else 
      exit 1
    fi