{{- if .Values.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "trust-anchor.labels" . | nindent 4 }}
data:
  mysql-root-password: {{ randAlphaNum 30 | b64enc | quote }}
  mysql-replication-password: {{ randAlphaNum 30 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}