apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        file /etc/coredns/nip.db 127.0.0.1.nip.io
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.17.0.2 k3s
  # in order to make the nip.io served local host addresses also available cluster internal(e.g. to the pods), we instruct coredns
  # to forward all such requests inside the cluster to the traefik' loadbalancer-service
  nip.db: |
    127.0.0.1.nip.io. IN SOA sns.dns.icann.org. noc.dns.icann.org. 2015082541 7200 3600 1209600 3600
    127.0.0.1.nip.io. IN NS    a.iana-servers.net.
    127.0.0.1.nip.io. IN NS    b.iana-servers.net.
    *.127.0.0.1.nip.io. IN CNAME traefik-loadbalancer.infra.svc.cluster.local.